// Mercately — Changelog data (sincronizado con server.py)
// type ∈ "new" | "improvement" | "fix" | "api" | "mobile"
const CHANGELOG = [
  {
    id: "v3-9-0",
    version: "v3.9.0",
    date: "20 May 2026",
    dateISO: "2026-05-20",
    month: "Mayo 2026",
    featured: true,
    tags: ["new", "api"],
    title: "MIA 2.0 — Agente IA con base de conocimiento propia",
    lede: "Conecta tu catálogo, PDFs y FAQ a MIA y deja que responda preguntas frecuentes en segundos con traspaso automático a un agente humano cuando detecta intención de compra.",
    media: { kind: "screenshot", label: "MIA · Vista de entrenamiento y handoff" },
    points: [
      { b: "Entrenamiento en 1 clic", t: "Sube documentos, URLs o tu catálogo y MIA arma su contexto sin código." },
      { b: "Handoff inteligente", t: "Detecta intención de compra y asigna el chat al agente correcto con el resumen completo." },
      { b: "Personalidad configurable", t: "Elige entre tono Formal, Informal o Cálido para que MIA hable como tu marca." },
      { b: "Métricas de calidad", t: "Cada respuesta queda etiquetada (resuelta, escalada, sin info) para mejorar el modelo." },
    ],
    author: { name: "Equipo Producto", initials: "EP" },
    readTime: "4 min de lectura",
  },
  {
    id: "v3-8-5",
    version: "v3.8.5",
    date: "08 May 2026",
    dateISO: "2026-05-08",
    month: "Mayo 2026",
    featured: false,
    tags: ["new"],
    title: "Performance Hub — ROAS en tiempo real desde WhatsApp",
    lede: "Conecta Meta Ads, WhatsApp y tu CRM en un solo panel. Mercately detecta el origen de cada conversación y calcula cuánto ganás por cada dólar invertido en pauta, sin Excel.",
    media: { kind: "screenshot", label: "Performance Hub · Panel de atribución" },
    points: [
      { b: "ROAS por campaña", t: "Ve exactamente qué anuncio generó ventas, no solo clics." },
      { b: "CAPI nativo", t: "Envía datos reales de conversión a Meta para mejorar el algoritmo de tus campañas." },
      { b: "Sin Excel", t: "Toda la atribución dentro del dashboard — sin exportar ni cruzar hojas manualmente." },
    ],
    author: { name: "Growth", initials: "GR" },
    readTime: "3 min",
  },
  {
    id: "v3-8-2",
    version: "v3.8.2",
    date: "22 Abr 2026",
    dateISO: "2026-04-22",
    month: "Abril 2026",
    featured: false,
    tags: ["improvement", "mobile"],
    title: "Bandeja multiagente rediseñada + app móvil 2.3× más rápida",
    lede: "Nuevo orden de columnas, asignación con un swipe y notificaciones agrupadas por cliente. La app ahora carga 2.3× más rápido en conexiones lentas.",
    media: { kind: "mobile", label: "App iOS · Inbox multiagente v3" },
    points: [
      { b: "Swipe-to-assign", t: "Desliza un chat para asignarlo a un compañero o a un equipo en un gesto." },
      { b: "Asignación inteligente", t: "Distribuye conversaciones por disponibilidad, keyword o canal automáticamente." },
      { b: "Modo concentración", t: "Silencia conversaciones de baja prioridad durante tus horas pico." },
    ],
    author: { name: "Mobile Team", initials: "MT" },
    readTime: "2 min",
  },
  {
    id: "v3-8-0",
    version: "v3.8.0",
    date: "07 Abr 2026",
    dateISO: "2026-04-07",
    month: "Abril 2026",
    featured: false,
    tags: ["new"],
    title: "Pagos digitales dentro del chat — Nequi, Daviplata y Bre-B",
    lede: "Cobra dentro de WhatsApp enviando un link de pago que se cierra en la misma conversación. Compatible con Nequi, Daviplata, Bre-B, tarjetas y más métodos locales.",
    media: { kind: "screenshot", label: "Pagos · Link de cobro en chat" },
    points: [
      { b: "Sin salir del chat", t: "El cliente paga desde WhatsApp sin redireccionamientos externos." },
      { b: "Conciliación automática", t: "Cada pago aprobado actualiza el estado del pedido en el CRM." },
      { b: "Multimoneda", t: "USD, MXN, COP, ARS, PEN, CLP y BRL nativos con conversión en vivo." },
    ],
    author: { name: "Payments", initials: "PG" },
    readTime: "4 min",
  },
  {
    id: "v3-7-4",
    version: "v3.7.4",
    date: "15 Mar 2026",
    dateISO: "2026-03-15",
    month: "Marzo 2026",
    featured: false,
    tags: ["improvement"],
    title: "Campañas de WhatsApp con segmentación avanzada y agendamiento",
    lede: "Segmenta tu audiencia con múltiples filtros combinados (etiquetas, etapa del funnel, canal) y agenda el envío para el momento de mayor apertura.",
    points: [
      { b: "Segmentación combinada", t: "Filtra por etiqueta, etapa del embudo, canal y última interacción a la vez." },
      { b: "Agendamiento inteligente", t: "Programa campañas para días y horas específicas sin estar conectado." },
      { b: "Analítica de campaña", t: "Tasa de apertura, respuestas y conversiones en un solo panel." },
    ],
    author: { name: "Equipo Producto", initials: "EP" },
    readTime: "3 min",
  },
  {
    id: "v3-7-0",
    version: "v3.7.0",
    date: "24 Feb 2026",
    dateISO: "2026-02-24",
    month: "Febrero 2026",
    featured: false,
    tags: ["new"],
    title: "Chatbots visuales con bloques drag-and-drop",
    lede: "Reemplazamos el editor lineal por un canvas drag-and-drop con ramas condicionales, variables del cliente y disparadores por palabra clave o evento.",
    media: { kind: "flow", label: "Editor de chatbot · Vista canvas" },
    points: [
      { b: "+20 bloques nativos", t: "Mensaje, pregunta, condición, llamada HTTP, asignar agente, esperar evento, etc." },
      { b: "Testing en vivo", t: "Simula un chat completo dentro del editor antes de publicar." },
      { b: "Versiones con rollback", t: "Cada publicación se guarda; vuelve a cualquier versión anterior en 1 clic." },
    ],
    author: { name: "Equipo Producto", initials: "EP" },
    readTime: "5 min",
  },
  {
    id: "v3-6-3",
    version: "v3.6.3",
    date: "10 Feb 2026",
    dateISO: "2026-02-10",
    month: "Febrero 2026",
    featured: false,
    tags: ["fix"],
    title: "Correcciones de estabilidad y mejoras de rendimiento",
    lede: "Atacamos los bugs más votados de la comunidad: adjuntos grandes, plantillas con variables y contadores de no leídos en Safari.",
    points: [
      { b: "Fix", t: "Los archivos adjuntos > 10 MB ya no truncan al reenviar a otro chat." },
      { b: "Fix", t: "Las plantillas con variables {{n}} se renderizan correctamente en la vista previa." },
      { b: "Fix", t: "El contador de no leídos ahora se reinicia correctamente al cerrar sesión en Safari." },
      { b: "Fix", t: "Las etiquetas con ñ y acentos se filtran correctamente en el buscador." },
    ],
    author: { name: "Quality", initials: "QA" },
    readTime: "2 min",
  },
  {
    id: "v3-6-0",
    version: "v3.6.0",
    date: "20 Ene 2026",
    dateISO: "2026-01-20",
    month: "Enero 2026",
    featured: false,
    tags: ["new", "api"],
    title: "Catálogo digital + carrito persistente por cliente",
    lede: "Cada cliente conserva su carrito entre conversaciones y dispositivos. Sincronización bidireccional con Shopify y WooCommerce.",
    media: { kind: "catalog", label: "Catálogo · Producto en chat" },
    points: [
      { b: "Importación masiva", t: "Sube tu catálogo desde Shopify, WooCommerce o CSV en menos de 5 minutos." },
      { b: "Stock en vivo", t: "Inventario sincronizado en tiempo real con bloqueo durante el checkout." },
      { b: "API de catálogo", t: "Endpoints para crear, actualizar y desactivar productos desde tu sistema." },
    ],
    author: { name: "Commerce", initials: "CM" },
    readTime: "4 min",
  },
  {
    id: "v3-5-0",
    version: "v3.5.0",
    date: "05 Ene 2026",
    dateISO: "2026-01-05",
    month: "Enero 2026",
    featured: false,
    tags: ["new", "api"],
    title: "API REST v3 — documentación OpenAPI y SDKs oficiales",
    lede: "Una sola URL base (api.mercately.com/v3) para todos los recursos. Versionado semántico, paginación cursor-based y documentación interactiva.",
    points: [
      { b: "OpenAPI 3.1", t: "Documentación interactiva y SDKs autogenerados para JS, Python, PHP y Ruby." },
      { b: "Rate limits claros", t: "60 req/s en Pro, 200 req/s en Enterprise con headers X-RateLimit-*." },
      { b: "Webhooks v3", t: "Firma HMAC-SHA256 en cada payload para verificar autenticidad del origen." },
    ],
    author: { name: "Developer Relations", initials: "DR" },
    readTime: "5 min",
  },
];

const TAG_LABEL = {
  new:         { label: "Nuevo",      cls: "t-new" },
  improvement: { label: "Mejora",     cls: "t-imp" },
  fix:         { label: "Corrección", cls: "t-fix" },
  api:         { label: "API",        cls: "t-api" },
  mobile:      { label: "Móvil",      cls: "t-mob" },
};
